service:
  name: auction

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    AUCTION_TABLE_NAME: ${self:custom.AuctionTable.name}
  iam:
    role:
      statements:
        - ${file(iam/AuctionTableIAM.yml):AuctionTableIAM}

resources:
  Resources:
    AuctionTable: ${file(resources/AuctionTable.yml):AuctionTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
  bidAuction:
    handler: src/handlers/bidAuction.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid
custom:
  AuctionTable:
    name: !Ref AuctionTable
    arn: !GetAtt AuctionTable.Arn
  bundle:
    linting: false
