AuctionTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: AuctionTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: endAt
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
